# Generated by Django 4.2 on 2023-04-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("roll", models.CharField(max_length=200)),
                ("department", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=200)),
            ],
        ),
    ]
